name: hellow world

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello STEP
        run: echo "hello world"
