name: testing
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened]
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm run test
